HIMALAYAS_API_RESPONSE = {
    "comments": "13/03/2026: The API has been updated.",
    "updatedAt": 1774692720,
    "offset": 0,
    "limit": 20,
    "totalCount": 2,
    "jobs": [
        {
            "title": "AI Operations Manager",
            "excerpt": "Lead AI operations for a fast-growing startup...",
            "companyName": "Acme AI",
            "companySlug": "acme-ai",
            "companyLogo": "https://cdn-images.himalayas.app/logo123",
            "employmentType": "Full Time",
            "minSalary": 150000,
            "maxSalary": 200000,
            "seniority": ["Senior"],
            "currency": "USD",
            "locationRestrictions": ["United States", "Canada"],
            "timezoneRestrictions": [-8, -7, -6, -5],
            "categories": ["Operations-Manager", "AI-Operations"],
            "parentCategories": ["Operations"],
            "description": "<p>Lead AI operations...</p>",
            "pubDate": 1774692720,
            "expiryDate": 1779876720,
            "applicationLink": "https://himalayas.app/companies/acme-ai/jobs/ai-operations-manager",
            "guid": "https://himalayas.app/companies/acme-ai/jobs/ai-operations-manager",
        },
        {
            "title": "DevRel Engineer",
            "excerpt": "Build developer community...",
            "companyName": "ToolCo",
            "companySlug": "toolco",
            "companyLogo": "https://cdn-images.himalayas.app/logo456",
            "employmentType": "Full Time",
            "minSalary": None,
            "maxSalary": None,
            "seniority": ["Mid-level"],
            "currency": "USD",
            "locationRestrictions": [],
            "timezoneRestrictions": [],
            "categories": ["Developer-Relations"],
            "parentCategories": [],
            "description": "<p>Build developer community...</p>",
            "pubDate": 1774692665,
            "expiryDate": 1779876664,
            "applicationLink": "https://himalayas.app/companies/toolco/jobs/devrel-engineer",
            "guid": "https://himalayas.app/companies/toolco/jobs/devrel-engineer",
        },
    ],
}
